const K={STORE_STATE:'bc-store-status-state',CHECK_STATE:'bc-report-check-state'},W='https://bot-config.erp-admin.workers.dev',C=W+'/config',A=W+'/api',UT='bc-update-tab-ids',DK='bc-device-id',PU='bc-pending-update';let cc=null,ct=0;chrome.storage.local.remove(K.CHECK_STATE).catch(()=>{});
const vp=v=>String(v||'0').split(/[.+-]/)[0].split('.').map(x=>Number(x)||0),vc=(a,b)=>{const A=vp(a),B=vp(b),n=Math.max(A.length,B.length);for(let i=0;i<n;i++){const d=(A[i]||0)-(B[i]||0);if(d)return d>0?1:-1}return 0};
async function cfg(force=false){if(!force&&cc&&Date.now()-ct<15000)return cc;const r=await fetch(C,{cache:'no-store'}),x=await r.json().catch(()=>({}));if(!r.ok||!x?.ok)throw Error(x?.error||'Не мога да прочета конфигурацията');cc=x;ct=Date.now();return x}
async function deviceId(){const x=await chrome.storage.local.get(DK);if(x[DK])return x[DK];const id=crypto.randomUUID?crypto.randomUUID():'pc-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2);await chrome.storage.local.set({[DK]:id});return id}
function vs(c){const current=chrome.runtime.getManifest().version,stable=String(c?.stableVersion||c?.latestVersion||'').trim(),latest=String(c?.latestVersion||stable).trim(),allowed=(Array.isArray(c?.allowedVersions)?c.allowedVersions:[stable]).map(x=>String(x||'').trim()).filter(Boolean),data={currentVersion:current,stableVersion:stable,latestVersion:latest,candidateVersion:String(c?.candidateVersion||'').trim()||null,allowedVersions:allowed,updateAvailable:!!latest&&vc(latest,current)>0,updatedAt:c?.updatedAt||null};if(!allowed.length)return{ok:false,error:'Липсват разрешени версии',code:'VERSION_CONFIG_ERROR',data};if(!allowed.includes(current))return{ok:false,error:`Версия ${current} не е разрешена. Разрешени: ${allowed.join(', ')}.`,code:'UPDATE_REQUIRED',data};return{ok:true,data}}
async function rememberTab(id){if(!Number.isInteger(id))return;const x=await chrome.storage.local.get(UT),a=Array.isArray(x[UT])?x[UT]:[];if(!a.includes(id))await chrome.storage.local.set({[UT]:[...a,id].slice(-20)})}
async function reloadRememberedTabs(){const x=await chrome.storage.local.get(UT),a=Array.isArray(x[UT])?x[UT]:[];await chrome.storage.local.remove(UT);await Promise.allSettled(a.filter(Number.isInteger).map(id=>chrome.tabs.reload(id)))}
async function update(c,manual=true,tabId=null){const s=vs(c);if(s.ok&&!s.data.updateAvailable)return{ok:true,data:{...s.data,status:'current'}};await rememberTab(tabId);try{const r=await chrome.runtime.requestUpdateCheck();if(r?.status==='update_available')return{ok:true,data:{...s.data,status:'update_available',availableVersion:r.version||s.data.latestVersion}};if(r?.status==='throttled')return{ok:true,data:{...s.data,status:'throttled'}}}catch{}return{ok:false,error:'Новата версия още не е налична от Chrome Web Store.',code:'UPDATE_UNAVAILABLE',data:s.data}}
const STARTS_WORK=new Set(['POST /run/start','POST /store-status/create','POST /store-status/post']);
async function pendingUpdate(){const x=await chrome.storage.local.get(PU);return!!x[PU]}
async function backendBusy(){try{const r=await api('/health','GET');if(!r.ok)return r.code==='UPDATE_REQUIRED'?false:true;const d=r.data||{};return!!(d.running||d.storeBusy||Number(d.activeJobs)>0||d.draining)}catch{return true}}
async function tryApplyPendingUpdate(){if(!await pendingUpdate())return false;if(await backendBusy())return false;await chrome.storage.local.remove(PU);chrome.runtime.reload();return true}
async function stageUpdate(){await chrome.storage.local.set({[PU]:true});await tryApplyPendingUpdate()}
async function api(path,method='GET',body){method=String(method||'GET').toUpperCase();if(STARTS_WORK.has(`${method} ${path}`)&&await pendingUpdate())return{ok:false,error:'Има готова актуализация. Изчаквам текущата операция и няма да стартирам нова.',code:'UPDATE_DRAINING'};let c=await cfg(),s=vs(c);if(!s.ok){cc=null;c=await cfg(true);s=vs(c);if(!s.ok)return s}const id=await deviceId(),r=await fetch(A+path,{method,headers:{'Content-Type':'application/json','X-Client-Version':chrome.runtime.getManifest().version,'X-Device-Id':id},body:body?JSON.stringify(body):undefined,cache:'no-store'}),data=await r.json().catch(()=>({error:`HTTP ${r.status}`}));if(r.status===426){cc=null;const f=await cfg(true).catch(()=>null),st=f?vs(f):null;return{ok:false,error:data?.error||st?.error||'Нужна е актуализация',code:'UPDATE_REQUIRED',data:{...(st?.data||{}),...(data||{})}}}return{ok:r.ok,data,error:r.ok?undefined:(data?.error||`HTTP ${r.status}`)}}
async function auto(){try{const c=await cfg(true),s=vs(c);if((!s.ok&&s.code==='UPDATE_REQUIRED')||s.data?.updateAvailable)await update(c,false)}catch{}}
chrome.runtime.onUpdateAvailable.addListener(()=>{stageUpdate().catch(()=>{})});chrome.runtime.onStartup.addListener(auto);chrome.runtime.onInstalled.addListener(d=>{chrome.storage.local.remove(PU).catch(()=>{});auto();if(d.reason==='update')reloadRememberedTabs().catch(()=>{})});
chrome.runtime.onMessage.addListener((m,s,reply)=>{if(!['API','STORE_STATE','CHECK_STATE','VERSION','UPDATE','AUTO_UPDATE','HEARTBEAT'].includes(m.type))return;(async()=>{try{
 if(m.type==='STORE_STATE'||m.type==='CHECK_STATE'){const key=K[m.type],st=chrome.storage.session;if(m.action==='get'){const x=await st.get(key);return reply({ok:true,data:x[key]||null})}if(m.action==='set'){await st.set({[key]:m.data});return reply({ok:true})}if(m.action==='clear'){await st.remove(key);return reply({ok:true})}throw Error('Невалидна state операция')}
 if(m.type==='HEARTBEAT'){const r=await api('/client/heartbeat','POST',{page:true});reply(r);if(await pendingUpdate())setTimeout(()=>{tryApplyPendingUpdate().catch(()=>{})},0);return}
 const c=await cfg(m.type==='VERSION'||m.type==='UPDATE'||m.type==='AUTO_UPDATE');if(m.type==='VERSION')return reply(vs(c));if(m.type==='UPDATE')return reply(await update(c,true,s.tab?.id));if(m.type==='AUTO_UPDATE')return reply(await update(c,false,s.tab?.id));reply(await api(m.path,m.method||'GET',m.body))
 }catch(e){reply({ok:false,error:e.message||'Сървърът не е достъпен',code:'VERSION_CHECK_FAILED'})}})();return true});