(()=>{
 if(top!==window)return;
 const E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const api=(path,body)=>new Promise((ok,no)=>chrome.runtime.sendMessage({type:'API',path,method:body?'POST':'GET',body},r=>{const e=chrome.runtime.lastError?.message;if(e)no(Error(e));else r?.ok?ok(r.data):no(Error(r?.error||r?.data?.error||'Операцията не успя'))}));
 const css=`
 .sm{min-width:900px;height:100%;min-height:0;display:flex;flex-direction:column}
 .sm-top{display:flex;align-items:center;gap:8px;margin-bottom:10px;min-width:0}
 .sm-city{flex:0 0 150px;min-width:150px;max-width:150px}
 .sm-search{flex:0 0 430px;min-width:280px;max-width:430px}
 .sm-tabs{display:inline-flex;flex:0 0 auto;gap:3px;background:#f3f7f6;border:1px solid #dce7e4;border-radius:10px;padding:3px;margin-left:2px}
 .sm-tab{height:32px;border:0;border-radius:7px;background:transparent;color:#60756f;padding:0 12px;font-weight:700;cursor:pointer;white-space:nowrap;transition:.16s ease}
 .sm-tab:hover{background:#eaf4f0;color:#276c5b}
 .sm-tab.active{background:#fff;color:#0b7d62;box-shadow:0 1px 5px #173b2f18}
 .sm-tab b{margin-left:5px;font-variant-numeric:tabular-nums}
 .sm select,.sm input{height:38px;border:1px solid #d9e4e2;border-radius:9px;background:#fff;padding:0 11px;color:#28463f;outline:0}
 .sm select:focus,.sm input:focus{border-color:#70af9f;box-shadow:0 0 0 3px #16805710}
 .sm-add{margin-left:auto;height:38px;display:inline-flex;align-items:center;justify-content:center;gap:8px;border:1px solid #087a60;border-radius:10px;background:linear-gradient(180deg,#119a78,#078564);color:#fff;padding:0 16px;font-weight:800;letter-spacing:.1px;box-shadow:0 2px 7px #0a7c5f22;cursor:pointer;transition:.16s ease;white-space:nowrap}
 .sm-add:hover:not(:disabled){transform:translateY(-1px);background:linear-gradient(180deg,#0f9171,#067a5d);box-shadow:0 5px 12px #0a7c5f2b}
 .sm-add:active:not(:disabled){transform:translateY(0);box-shadow:0 2px 6px #0a7c5f20}
 .sm-add-icon{width:20px;height:20px;border-radius:6px;background:#ffffff22;display:grid;place-items:center;font-size:18px;line-height:1;font-weight:500}
 .sm-msg{min-height:18px;margin:0 0 8px;color:#b74750;font-size:12px}
 .sm-head,.sm-row{display:grid;grid-template-columns:36px 90px 140px minmax(280px,1fr) 100px 62px;gap:8px;align-items:center;padding:0 10px}
 .sm-head{flex:0 0 40px;height:40px;background:#fbfcfc;border-bottom:1px solid #e4ebea;color:#526b65;font-size:11px;font-weight:700}
 .sm-list{flex:1;min-height:0;border:1px solid #dde7e5;border-radius:10px;background:#fff;overflow:hidden;display:flex;flex-direction:column}
 .sm-body{flex:1;min-height:0;overflow:auto;overscroll-behavior:contain;scrollbar-width:thin;scrollbar-color:#c5d6d2 transparent}
 .sm-row{min-height:49px;border-bottom:1px solid #edf1f0}.sm-row:last-child{border-bottom:0}.sm-row:hover{background:#fbfdfc}.sm-row b{font-variant-numeric:tabular-nums}.sm-name{white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
 .sm-active{display:flex;align-items:center;gap:6px;font-size:12px;color:#4f6962}.sm-active input{width:16px;height:16px}
 .sm-del{height:30px;border:1px solid #efcdd1;border-radius:7px;background:#fff5f5;color:#bc4550}.sm-del:hover:not(:disabled){background:#ffe9eb}
 .sm-add:disabled,.sm-del:disabled{background:#e8ecec!important;color:#8b9996!important;border-color:#d5dfdd!important;box-shadow:none!important;cursor:not-allowed!important;opacity:1!important;transform:none!important}.sm-active input:disabled{cursor:not-allowed;opacity:.5;filter:grayscale(1)}
 .sm-foot{flex:0 0 auto;display:flex;justify-content:flex-start;align-items:center;margin-top:10px;color:#7a8e89;font-size:11px}
 @media(max-width:1180px){.sm-search{flex-basis:340px}.sm-tab{padding:0 9px}}
 @media(max-width:980px){.sm{min-width:760px}.sm-top{flex-wrap:wrap}.sm-search{flex:1 1 360px;max-width:none}.sm-tabs{order:3}.sm-add{order:4;margin-left:auto}}
 `;
 function page(box){const city=box.querySelector('.sm-city').value,q=box.querySelector('.sm-search').value.trim().toLowerCase(),mode=box._status||'all',all=box._rows||[];return all.filter(s=>(!city||s.city===city)&&(mode==='all'||(mode==='active'?!!s.active:!s.active))&&(!q||[s.code,s.city,s.name].some(x=>String(x||'').toLowerCase().includes(q))))}
 function render(box){const rows=page(box),body=box.querySelector('.sm-body'),oldTop=body?.scrollTop||0,all=box._rows||[];for(const b of box.querySelectorAll('.sm-tab')){const m=b.dataset.status,c=m==='all'?all.length:all.filter(x=>m==='active'?x.active:!x.active).length;b.querySelector('b').textContent=c;b.classList.toggle('active',m===(box._status||'all'))}body.innerHTML=rows.map((s,i)=>`<div class="sm-row" data-code="${E(s.code)}"><span>${i+1}</span><b>${E(s.code)}</b><span>${E(s.city||'—')}</span><span class="sm-name" title="${E(s.name)}">${E(s.name)}</span><label class="sm-active"><input type="checkbox" ${s.active?'checked':''}> Активен</label><button class="sm-del" type="button">Изтрий</button></div>`).join('')||'<div style="padding:22px;color:#7b8f89">Няма магазини.</div>';box.querySelector('.sm-count').textContent=rows.length?`${rows.length} магазина`:'Няма магазини';if(body)body.scrollTop=Math.min(oldTop,Math.max(0,body.scrollHeight-body.clientHeight));box._syncLocks?.()}
 async function load(root){const box=root.querySelector('.sm');if(!box)return;const msg=box.querySelector('.sm-msg'),select=box.querySelector('.sm-city'),selected=select.value;msg.textContent='';try{const rows=await api('/stores');box._rows=rows;const cities=[...new Set(rows.map(s=>String(s.city||'').trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'bg'));select.innerHTML='<option value="">Всички градове</option>'+cities.map(c=>`<option value="${E(c)}">${E(c)} (${rows.filter(s=>s.city===c).length})</option>`).join('');if(cities.includes(selected))select.value=selected;render(box)}catch(e){msg.textContent=e.message}}
 function mount(){const host=document.getElementById('bc-store-modal'),root=host?.shadowRoot,page=root?.querySelector('.page-stores');if(!root||!page||page.dataset.ready)return;page.dataset.ready='1';const style=document.createElement('style');style.textContent=css;root.append(style);page.innerHTML=`<div class="sm"><div class="sm-top"><select class="sm-city"><option value="">Всички градове</option></select><input class="sm-search" placeholder="Код / име / адрес"><div class="sm-tabs"><button type="button" class="sm-tab active" data-status="all">Всички <b>0</b></button><button type="button" class="sm-tab" data-status="active">Активни <b>0</b></button><button type="button" class="sm-tab" data-status="inactive">Неактивни <b>0</b></button></div><button type="button" class="sm-add"><span class="sm-add-icon">+</span><span>Добави</span></button></div><p class="sm-msg"></p><div class="sm-list"><div class="sm-head"><span>#</span><span>Код</span><span>Град</span><span>Име / адрес</span><span>Статус</span><span></span></div><div class="sm-body"></div></div><div class="sm-foot"><span class="sm-count"></span></div></div>`;
  host.addEventListener('bc-store-page',e=>{if(e.detail?.page==='stores')load(root)});const box=page.querySelector('.sm');box._status='all';const blocked=()=>host.dataset.job==='1',syncLocks=()=>{const locked=blocked(),add=box.querySelector('.sm-add');if(add)add.disabled=locked;for(const x of box.querySelectorAll('.sm-active input,.sm-del'))x.disabled=locked};box._syncLocks=syncLocks;new MutationObserver(syncLocks).observe(host,{attributes:true,attributeFilter:['data-job']});syncLocks();
  box.querySelector('.sm-city').onchange=()=>{render(box);box.querySelector('.sm-body').scrollTop=0};box.querySelector('.sm-search').oninput=()=>{render(box);box.querySelector('.sm-body').scrollTop=0};box.querySelector('.sm-tabs').onclick=e=>{const b=e.target.closest('.sm-tab');if(!b)return;box._status=b.dataset.status;render(box);box.querySelector('.sm-body').scrollTop=0};
  const body=box.querySelector('.sm-body');let wheelLock=0;body.addEventListener('wheel',e=>{if(Math.abs(e.deltaY)<=Math.abs(e.deltaX))return;e.preventDefault();if(wheelLock)return;const row=body.querySelector('.sm-row');if(!row)return;const step=Math.max(1,row.getBoundingClientRect().height),dir=e.deltaY>0?1:-1,target=Math.max(0,Math.min(body.scrollTop+dir*step*3,body.scrollHeight-body.clientHeight));wheelLock=1;body.scrollTo({top:target,behavior:'auto'});setTimeout(()=>wheelLock=0,120)},{passive:false});
  box.querySelector('.sm-add').onclick=async()=>{if(blocked())return;const msg=box.querySelector('.sm-msg');msg.textContent='';const code=prompt('Код на магазина:','');if(code===null)return;const city=prompt('Град:','');if(city===null)return;const name=prompt('Име / адрес:','');if(name===null)return;if(!String(city).trim()){msg.textContent='Въведи град.';return}if(!String(name).trim()){msg.textContent='Въведи име / адрес.';return}try{await api('/stores/add',{code:String(code).trim(),city:String(city).trim(),name:String(name).trim()});await load(root);msg.style.color='#168057';msg.textContent='Магазинът е добавен.'}catch(e){msg.style.color='#b74750';msg.textContent=e.message}};
  box.querySelector('.sm-body').onchange=async e=>{if(blocked()||e.target.type!=='checkbox')return;const row=e.target.closest('.sm-row'),msg=box.querySelector('.sm-msg');try{await api('/stores/active',{code:row.dataset.code,active:e.target.checked});msg.style.color='#168057';msg.textContent='Запазено.'}catch(x){e.target.checked=!e.target.checked;msg.style.color='#b74750';msg.textContent=x.message}};
  box.querySelector('.sm-body').onclick=async e=>{const b=e.target.closest('.sm-del');if(!b||blocked())return;const code=b.closest('.sm-row').dataset.code;if(!confirm('Да изтрия ли магазин '+code+'?'))return;const msg=box.querySelector('.sm-msg');try{await api('/stores/delete',{code});await load(root);msg.style.color='#168057';msg.textContent='Магазинът е изтрит.'}catch(x){msg.style.color='#b74750';msg.textContent=x.message}};
 }
 setInterval(mount,250);mount();
})();
