(()=>{if(top!==window)return;const send=t=>new Promise(r=>chrome.runtime.sendMessage({type:t},x=>r(chrome.runtime.lastError?{ok:false,error:chrome.runtime.lastError.message,code:'RUNTIME_ERROR'}:(x||{ok:false,error:'Няма отговор'}))));let host=null,busy=false;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function remove(){host?.remove();host=null}
function show(r){remove();host=document.createElement('div');host.id='bc-version-guard';host.style.cssText='position:fixed;inset:0;z-index:2147483647';const root=host.attachShadow({mode:'closed'}),d=r?.data||{},old=r?.code==='UPDATE_REQUIRED';
 root.innerHTML=`<style>:host{all:initial}.m{position:fixed;inset:0;background:#132b3ed9;backdrop-filter:blur(5px);display:grid;place-items:center;font:14px/1.45 Segoe UI,Arial;color:#183237}.c{width:min(520px,calc(100vw - 32px));background:#fff;border:1px solid #d9e4e5;border-radius:18px;box-shadow:0 28px 90px #071c2666;padding:26px}.b{display:inline-flex;padding:5px 9px;border-radius:999px;background:#fff0f1;color:#b53542;font-size:11px;font-weight:800}.t{font-size:22px;font-weight:850;margin:12px 0 7px}.x{color:#60736f}.v{margin:18px 0;padding:12px 14px;border:1px solid #e1e9e8;border-radius:12px;background:#f7f9f9;display:grid;gap:7px}.r{display:flex;justify-content:space-between;gap:20px}.r b{color:#173d35}.a{display:flex;gap:9px;margin-top:18px}.q{height:42px;border-radius:10px;padding:0 16px;font:800 14px Segoe UI,Arial;cursor:pointer}.p{border:1px solid #087a60;background:#078564;color:#fff}.s{border:1px solid #d8e4e2;background:#fff;color:#2d6559}.q:disabled{cursor:wait;opacity:.65}.msg{min-height:19px;margin-top:12px;color:#697e79;font-size:12px}.e{color:#b53542}</style><div class="m"><div class="c"><span class="b">${old?'АКТУАЛИЗАЦИЯ ЗАДЪЛЖИТЕЛНА':'ДОСТЪПЪТ Е ЗАКЛЮЧЕН'}</span><div class="t">${old?'Има нова версия':'Не може да се провери версията'}</div><div class="x">${old?'Тази версия не може да се използва. Натисни „Актуализиране“.':'Екстеншънът не стартира без успешна проверка.'}</div>${old?`<div class="v"><div class="r"><span>Текуща версия</span><b>${esc(d.currentVersion||'—')}</b></div><div class="r"><span>Последна версия</span><b>${esc(d.latestVersion||'—')}</b></div></div>`:''}<div class="a">${old?'<button class="q p" data-a="update">Актуализиране</button>':''}<button class="q s" data-a="retry">Провери отново</button></div><div class="msg ${old?'':'e'}">${esc(r?.error||'')}</div></div></div>`;
 root.addEventListener('click',async e=>{const b=e.target.closest('[data-a]');if(!b||busy)return;busy=true;for(const x of root.querySelectorAll('button'))x.disabled=true;const m=root.querySelector('.msg');try{
  if(b.dataset.a==='retry'){m.textContent='Проверявам…';const x=await send('VERSION');if(x?.ok){remove();location.reload();return}show(x);return}
  m.classList.remove('e');m.textContent='Проверявам за актуализация…';const x=await send('UPDATE');if(!x.ok)throw Error(x.error||'Актуализацията не е достъпна');
  if(x.data?.status==='update_available')m.textContent='Новата версия е намерена. Chrome я инсталира…';else if(x.data?.status==='manual_opened')m.textContent='Отворена е последната версия.';else if(x.data?.status==='throttled')m.textContent='Chrome вече е проверявал. Актуализацията ще се приложи автоматично.';else if(x.data?.status==='current')location.reload();else m.textContent='Проверката приключи.';
 }catch(err){m.classList.add('e');m.textContent=err.message||String(err)}finally{busy=false;for(const x of root.querySelectorAll('button'))x.disabled=false}});
 document.documentElement.append(host)}
async function check(){const r=await send('VERSION');if(r?.ok){remove();return true}show(r);return false}
globalThis.__BC_VERSION_GATE__=check();globalThis.__BC_FORCE_VERSION_CHECK__=check;setInterval(check,30000)})();