(()=>{if(top!==window)return;const send=t=>new Promise(r=>chrome.runtime.sendMessage({type:t},x=>r(chrome.runtime.lastError?{ok:false,error:chrome.runtime.lastError.message,code:'RUNTIME_ERROR'}:(x||{ok:false,error:'Няма отговор'}))));let host=null,busy=false,retryTimer=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function clearRetry(){if(retryTimer){clearTimeout(retryTimer);retryTimer=null}}
function remove(){clearRetry();host?.remove();host=null}
function render(r,msg='Проверявам за актуализация…',error=false){host?.remove();host=document.createElement('div');host.id='bc-version-guard';host.style.cssText='position:fixed;inset:0;z-index:2147483647';const root=host.attachShadow({mode:'closed'}),d=r?.data||{},old=r?.code==='UPDATE_REQUIRED';
 root.innerHTML=`<style>:host{all:initial}.m{position:fixed;inset:0;background:#132b3ed9;backdrop-filter:blur(5px);display:grid;place-items:center;font:14px/1.45 Segoe UI,Arial;color:#183237}.c{width:min(520px,calc(100vw - 32px));background:#fff;border:1px solid #d9e4e5;border-radius:18px;box-shadow:0 28px 90px #071c2666;padding:26px}.b{display:inline-flex;padding:5px 9px;border-radius:999px;background:#fff0f1;color:#b53542;font-size:11px;font-weight:800}.t{font-size:22px;font-weight:850;margin:12px 0 7px}.x{color:#60736f}.v{margin:18px 0;padding:12px 14px;border:1px solid #e1e9e8;border-radius:12px;background:#f7f9f9;display:grid;gap:7px}.r{display:flex;justify-content:space-between;gap:20px}.r b{color:#173d35}.msg{margin-top:16px;color:${error?'#b53542':'#2d6559'};font-weight:700}.spin{display:inline-block;width:14px;height:14px;margin-right:8px;border:2px solid #b9d9d1;border-top-color:#078564;border-radius:50%;vertical-align:-2px;animation:s .8s linear infinite}@keyframes s{to{transform:rotate(360deg)}}</style><div class="m"><div class="c"><span class="b">${old?'АКТУАЛИЗАЦИЯ ЗАДЪЛЖИТЕЛНА':'ДОСТЪПЪТ Е ЗАКЛЮЧЕН'}</span><div class="t">${old?'Актуализирам автоматично':'Не може да се провери версията'}</div><div class="x">${old?'Тази версия е заключена. Не е нужно да натискаш нищо.':'Екстеншънът не стартира без успешна проверка.'}</div>${old?`<div class="v"><div class="r"><span>Текуща версия</span><b>${esc(d.currentVersion||'—')}</b></div><div class="r"><span>Нужна версия</span><b>${esc(d.latestVersion||'—')}</b></div></div>`:''}<div class="msg">${error?'':old?'<span class="spin"></span>':''}${esc(msg)}</div></div></div>`;
 document.documentElement.append(host)}
function retryLater(ms=300000){clearRetry();retryTimer=setTimeout(check,ms)}
async function autoUpdate(r){if(busy)return false;busy=true;render(r,'Проверявам Chrome Web Store…');try{
 const x=await send('AUTO_UPDATE');
 if(x?.ok&&x.data?.status==='current'){remove();location.reload();return true}
 if(x?.ok&&x.data?.status==='update_available'){render(r,`Намерена е версия ${x.data.availableVersion||x.data.latestVersion||''}. Chrome я инсталира автоматично…`);return false}
 if(x?.ok&&x.data?.status==='throttled'){render(r,'Chrome вече проверява за обновяване. Ще продължа автоматично.');retryLater();return false}
 render(r,'Новата версия още не е налична от Chrome Web Store. Ще опитам пак автоматично.');retryLater();return false
 }catch(e){render(r,e.message||'Неуспешна проверка за актуализация.',true);retryLater();return false}finally{busy=false}}
async function check(){const r=await send('VERSION');if(r?.ok){remove();return true}if(r?.code==='UPDATE_REQUIRED')return autoUpdate(r);render(r,r?.error||'Не може да се провери версията.',true);retryLater(60000);return false}
chrome.runtime.onMessage.addListener(m=>{if(m?.type==='BC_VERSION_REQUIRED'&&m.result?.code==='UPDATE_REQUIRED')autoUpdate(m.result)});
globalThis.__BC_VERSION_GATE__=check();globalThis.__BC_FORCE_VERSION_CHECK__=check;})();