const fs=require('fs'),path=require('path'),DB=path.join(__dirname,'data','stores.db');
const norm=s=>String(s||'').normalize('NFKC').toLocaleLowerCase('bg-BG').replace(/(?:^|\s)(?:м|ем|г)\s*-\s*/g,' ').replace(/[„“"'.,;:^/\\()[\]{}-]+/g,' ').replace(/\s+/g,' ').trim();
function key(city,name){const c=norm(city),n=norm(name),x=n===c?'':n.startsWith(c+' ')?n.slice(c.length).trim():n;return c+'|'+x}
function open(){
 let DatabaseSync;try{({DatabaseSync}=require('node:sqlite'))}catch{throw Error('За stores.db е нужен Node.js 22.5 или по-нов')}
 fs.mkdirSync(path.dirname(DB),{recursive:true});let db;
 try{
  db=new DatabaseSync(DB);db.exec("CREATE TABLE IF NOT EXISTS stores(code TEXT PRIMARY KEY CHECK(length(code)=6 AND code NOT GLOB '*[^0-9]*'),name TEXT NOT NULL CHECK(length(trim(name))>0),city TEXT NOT NULL DEFAULT '',active INTEGER NOT NULL DEFAULT 1 CHECK(active IN(0,1)),store_key TEXT NOT NULL DEFAULT '')");
  const cols=db.prepare('PRAGMA table_info(stores)').all();if(!cols.some(x=>x.name==='city'))db.exec("ALTER TABLE stores ADD COLUMN city TEXT NOT NULL DEFAULT ''");if(!cols.some(x=>x.name==='store_key'))db.exec("ALTER TABLE stores ADD COLUMN store_key TEXT NOT NULL DEFAULT ''");
  db.exec('DROP INDEX IF EXISTS stores_unique_location');const rows=db.prepare('SELECT code,city,name FROM stores ORDER BY code').all(),seen=new Set(),del=db.prepare('DELETE FROM stores WHERE code=?'),upd=db.prepare('UPDATE stores SET store_key=? WHERE code=?');db.exec('BEGIN');try{for(const r of rows){const k=key(r.city,r.name);if(seen.has(k))del.run(r.code);else{seen.add(k);upd.run(k,r.code)}}db.exec('COMMIT')}catch(e){db.exec('ROLLBACK');throw e}db.exec('CREATE UNIQUE INDEX IF NOT EXISTS stores_unique_location ON stores(store_key)');return db
 }catch(e){try{db?.close()}catch{}if(/file is not a database/i.test(e.message))throw Error('stores.db не е валидна SQLite база.');throw e}
}
const row=x=>({code:String(x.code),name:String(x.name),city:String(x.city||''),active:!!x.active});
function listStores(active=false){const db=open();try{return db.prepare(`SELECT code,name,city,active FROM stores${active?' WHERE active=1':''} ORDER BY city,name,code`).all().map(row)}finally{db.close()}}
const getStores=()=>listStores(true);
function data(body){const code=String(body?.code||'').trim(),name=String(body?.name||'').trim(),city=String(body?.city||'').trim();if(!/^\d{6}$/.test(code))throw Object.assign(Error('Кодът трябва да е 6 цифри'),{status:400});if(!city)throw Object.assign(Error('Избери град'),{status:400});if(!name)throw Object.assign(Error('Въведи име / адрес на магазина'),{status:400});return{code,name,city,storeKey:key(city,name)}}
function addStore(body){const{code,name,city,storeKey}=data(body),db=open();try{if(db.prepare('SELECT 1 FROM stores WHERE code=?').get(code))throw Object.assign(Error('Магазин '+code+' вече съществува'),{status:409});const d=db.prepare('SELECT code FROM stores WHERE store_key=?').get(storeKey);if(d)throw Object.assign(Error('Този магазин вече съществува с код '+d.code),{status:409});db.prepare('INSERT INTO stores(code,name,city,active,store_key) VALUES(?,?,?,1,?)').run(code,name,city,storeKey);return{code,name,city,active:true}}finally{db.close()}}
function setActive(body){const code=String(body?.code||'').trim(),active=body?.active?1:0;if(!/^\d{6}$/.test(code))throw Object.assign(Error('Невалиден код'),{status:400});const db=open();try{const r=db.prepare('UPDATE stores SET active=? WHERE code=?').run(active,code);if(!Number(r.changes))throw Object.assign(Error('Магазинът не е намерен'),{status:404});return{code,active:!!active}}finally{db.close()}}
function deleteStore(body){const code=String(body?.code||'').trim();if(!/^\d{6}$/.test(code))throw Object.assign(Error('Невалиден код'),{status:400});const db=open();try{const r=db.prepare('DELETE FROM stores WHERE code=?').run(code);if(!Number(r.changes))throw Object.assign(Error('Магазинът не е намерен'),{status:404});return{code,deleted:true}}finally{db.close()}}
function upsertStores(rows){const db=open();try{const q=db.prepare('INSERT INTO stores(code,name,city,active,store_key) VALUES(?,?,?,1,?) ON CONFLICT(code) DO UPDATE SET name=excluded.name,city=excluded.city,store_key=excluded.store_key');db.exec('BEGIN');try{for(const x of rows){const{code,name,city,storeKey}=data(x),d=db.prepare('SELECT code FROM stores WHERE store_key=? AND code<>?').get(storeKey,code);if(d)throw Error('Дублиран магазин: '+code+' / '+d.code);q.run(code,name,city,storeKey)}db.exec('COMMIT')}catch(e){db.exec('ROLLBACK');throw e}return rows.length}finally{db.close()}}
module.exports={getStores,listStores,addStore,setActive,deleteStore,upsertStores};
