const DEFAULT_CONFIG={backend:null,stableVersion:'1.1.7',latestVersion:'1.1.7',candidateVersion:null,allowedVersions:['1.1.7'],updateUrl:'',updatedAt:null};
const CORS={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'GET,POST,PUT,DELETE,OPTIONS','Access-Control-Allow-Headers':'Content-Type,Authorization,X-Client-Version,X-Device-Id','Access-Control-Max-Age':'86400'};
const json=(data,status=200,extra={})=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json; charset=utf-8',...CORS,...extra}});
const validVersion=v=>/^\d+\.\d+\.\d+$/.test(String(v||'').trim());
function validBackend(v){try{const u=new URL(String(v||''));return u.protocol==='https:'&&/\.trycloudflare\.com$/i.test(u.hostname)}catch{return false}}
const authorized=(request,env)=>!!env.ADMIN_TOKEN&&(request.headers.get('Authorization')||'')===`Bearer ${env.ADMIN_TOKEN}`;
const store=env=>env.CONFIG||env.BOT_CONFIG||env.CONFIG_KV;
function normalize(raw={}){const old=String(raw.latestVersion||raw.minimumVersion||DEFAULT_CONFIG.latestVersion),stable=validVersion(raw.stableVersion)?String(raw.stableVersion):validVersion(old)?old:DEFAULT_CONFIG.stableVersion,latest=validVersion(raw.latestVersion)?String(raw.latestVersion):stable,candidate=validVersion(raw.candidateVersion)?String(raw.candidateVersion):null,allowed=(Array.isArray(raw.allowedVersions)?raw.allowedVersions:[stable]).map(String).filter(validVersion);if(!allowed.includes(stable))allowed.unshift(stable);return{backend:validBackend(raw.backend)?String(raw.backend):null,stableVersion:stable,latestVersion:allowed.includes(latest)?latest:stable,candidateVersion:candidate,allowedVersions:[...new Set(allowed)],updateUrl:String(raw.updateUrl||''),updatedAt:raw.updatedAt||null}}
async function readConfig(env){const kv=store(env);if(!kv)return normalize(DEFAULT_CONFIG);try{return normalize({...DEFAULT_CONFIG,...JSON.parse(await kv.get('app-config')||'{}')})}catch{return normalize(DEFAULT_CONFIG)}}
async function writeConfig(env,c){const kv=store(env);if(!kv)throw Error('Липсва KV binding CONFIG');await kv.put('app-config',JSON.stringify(c));return c}
function publicConfig(c){return{ok:true,stableVersion:c.stableVersion,latestVersion:c.latestVersion,candidateVersion:c.candidateVersion,allowedVersions:c.allowedVersions,minimumVersion:c.stableVersion,updateUrl:c.updateUrl||'',updatedAt:c.updatedAt,backendReady:!!c.backend}}
async function updateConfig(request,env){if(!authorized(request,env))return json({ok:false,error:'Невалиден администраторски достъп'},401);let b={};try{b=await request.json()}catch{return json({ok:false,error:'Невалиден JSON'},400)}const c=await readConfig(env),n={...c};if(Object.hasOwn(b,'backend')){if(b.backend!==null&&!validBackend(b.backend))return json({ok:false,error:'Невалиден backend URL'},400);n.backend=b.backend||null}if(Object.hasOwn(b,'stableVersion')){if(!validVersion(b.stableVersion))return json({ok:false,error:'Невалидна stableVersion'},400);n.stableVersion=String(b.stableVersion)}if(Object.hasOwn(b,'candidateVersion')){if(b.candidateVersion!==null&&!validVersion(b.candidateVersion))return json({ok:false,error:'Невалидна candidateVersion'},400);n.candidateVersion=b.candidateVersion?String(b.candidateVersion):null}if(Object.hasOwn(b,'allowedVersions')){if(!Array.isArray(b.allowedVersions)||!b.allowedVersions.length||b.allowedVersions.some(x=>!validVersion(x)))return json({ok:false,error:'Невалидни allowedVersions'},400);n.allowedVersions=[...new Set(b.allowedVersions.map(String))]}if(Object.hasOwn(b,'latestVersion')){if(!validVersion(b.latestVersion))return json({ok:false,error:'Невалидна latestVersion'},400);n.latestVersion=String(b.latestVersion)}if(Object.hasOwn(b,'updateUrl'))n.updateUrl=String(b.updateUrl||'');if(!n.allowedVersions.includes(n.stableVersion))return json({ok:false,error:'stableVersion трябва да е в allowedVersions'},400);if(!n.allowedVersions.includes(n.latestVersion))return json({ok:false,error:'latestVersion трябва да е в allowedVersions'},400);n.updatedAt=new Date().toISOString();await writeConfig(env,n);return json(publicConfig(n))}
function clientMeta(request){const cf=request.cf||{},enc=v=>encodeURIComponent(String(v||''));return{ip:request.headers.get('CF-Connecting-IP')||'',country:enc(cf.country),region:enc(cf.region),city:enc(cf.city),ua:request.headers.get('User-Agent')||''}}
async function proxy(request,env,url,c){if(!env.ADMIN_TOKEN)return json({ok:false,error:'ADMIN_TOKEN липсва'},500);if(!c.backend)return json({ok:false,error:'Backend-ът не е свързан'},503);const current=String(request.headers.get('X-Client-Version')||'').trim();if(!validVersion(current)||!c.allowedVersions.includes(current))return json({ok:false,error:`Версия ${current||'—'} не е разрешена. Разрешени: ${c.allowedVersions.join(', ')}.`,code:'UPDATE_REQUIRED',currentVersion:current||null,stableVersion:c.stableVersion,latestVersion:c.latestVersion,candidateVersion:c.candidateVersion,allowedVersions:c.allowedVersions},426);const target=new URL(c.backend);target.pathname=url.pathname.replace(/^\/api/,'')||'/';target.search=url.search;const h=new Headers(request.headers),m=clientMeta(request);h.set('X-Bot-Token',env.ADMIN_TOKEN);h.set('X-Client-Version',current);h.set('X-Client-IP',m.ip);h.set('X-Client-Country',m.country);h.set('X-Client-Region',m.region);h.set('X-Client-City',m.city);h.set('X-Client-UA',m.ua);h.delete('Authorization');h.delete('CF-Connecting-IP');const r=await fetch(target.toString(),{method:request.method,headers:h,body:['GET','HEAD'].includes(request.method)?undefined:request.body,redirect:'manual'});const out=new Headers(r.headers);for(const[k,v]of Object.entries(CORS))out.set(k,v);return new Response(r.body,{status:r.status,statusText:r.statusText,headers:out})}
export default{async fetch(request,env){if(request.method==='OPTIONS')return new Response(null,{status:204,headers:CORS});const url=new URL(request.url),c=await readConfig(env);if(url.pathname==='/config'){if(request.method==='GET')return json(publicConfig(c));if(request.method==='PUT')return updateConfig(request,env);return json({ok:false,error:'Method not allowed'},405)}if(url.pathname==='/health')return json({ok:true,worker:true,...publicConfig(c)});if(url.pathname.startsWith('/api/'))return proxy(request,env,url,c);return json({ok:false,error:'Not found'},404)}};